name: Docker Build

on:
  push:
    branches:
      - '**'
    paths:
      - 'Dockerfile'
      - 'docker-*'

env:
  USERNAME: akafeng
  REPOSITORY: shadowsocks
  GITHUB_PACKAGE_REGISTRY: docker.pkg.github.com

jobs:
  build:
    name: Build Testing
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Docker Login
        run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ${{ env.GITHUB_PACKAGE_REGISTRY }} -u ${{ env.USERNAME }} --password-stdin

      - name: Docker Build
        env:
          STAGE_CACHE: ${{ env.GITHUB_PACKAGE_REGISTRY }}/${{ github.repository }}/${{ env.REPOSITORY }}:stage
        run: |
          docker build \
            --target builder \
            --tag=${{ env.STAGE_CACHE }} \
            .
          docker build \
            --cache-from=${{ env.STAGE_CACHE }} \
            .

      - name: Docker Publish
        run: docker push --all-tags ${{ env.GITHUB_PACKAGE_REGISTRY }}/${{ github.repository }}/${{ env.REPOSITORY }}
