name: Docker Publish

on:
  release:
    types:
      - published

env:
  USERNAME: akafeng
  REPOSITORY: shadowsocks
  GITHUB_PACKAGE_REGISTRY: docker.pkg.github.com

jobs:
  publish:
    name: Publish Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.1.0

      - name: Process Version
        id: version
        uses: ncipollo/semantic-version-action@v1

      - name: Docker Login
        run: |
          echo ${{ secrets.GITHUB_TOKEN }} | docker login ${{ env.GITHUB_PACKAGE_REGISTRY }} -u ${{ env.USERNAME }} --password-stdin
          echo ${{ secrets.DOCKER_TOKEN }} | docker login -u ${{ env.USERNAME }} --password-stdin

      - name: Docker Build
        env:
          STAGE_CACHE: ${{ env.GITHUB_PACKAGE_REGISTRY }}/${{ github.repository }}/${{ env.REPOSITORY }}:stage
          LATEST_TAG: ${{ env.USERNAME }}/${{ env.REPOSITORY }}:latest
          MAJOR_TAG: ${{ env.USERNAME }}/${{ env.REPOSITORY }}:${{ steps.version.outputs.major }}
          MINOR_TAG: ${{ env.USERNAME }}/${{ env.REPOSITORY }}:${{ steps.version.outputs.major }}.${{ steps.version.outputs.minor }}
          PATCH_TAG: ${{ env.USERNAME }}/${{ env.REPOSITORY }}:${{ steps.version.outputs.major }}.${{ steps.version.outputs.minor }}.${{ steps.version.outputs.patch }}
        run: |
          docker pull ${{ env.STAGE_CACHE }} || true
          docker pull ${{ env.LATEST_TAG }} || true
          docker build \
            --cache-from=${{ env.STAGE_CACHE }},${{ env.LATEST_TAG }} \
            --tag=${{ env.LATEST_TAG }} \
            --tag=${{ env.MAJOR_TAG }} \
            --tag=${{ env.MINOR_TAG }} \
            --tag=${{ env.PATCH_TAG }} \
            .

      - name: Docker Publish
        run: docker push ${{ env.USERNAME }}/${{ env.REPOSITORY }}
